[build-system]
requires = ["setuptools>=61", "wheel", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyvista_tools"
version = '0.1.0'

[tool.setuptools]
packages = ["pyvista_tools"]